name: Build and push Docker image

on:
  push:
    branches:
      - development # Automatic deploy for development branch
      - master

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-web-app .

      - name: Tag Docker image
        run: |
          docker tag my-web-app lirani5900/my-web-app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_HUB_USERNAME/my-web-app:latest

      # Deploy to development environment
      - name: Deploy to development
        if: github.ref == 'refs/heads/development'
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Build and push development environment
        if: github.ref == 'refs/heads/development'
        run: |
          docker buildx build --platform linux/amd64 -t $DOCKER_HUB_USERNAME/my-web-app:development --push .

      # Deploy to master environment
      - name: Deploy to master
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Build and push master environment
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        run: |
          docker buildx build --platform linux/amd64 -t $DOCKER_HUB_USERNAME/my-web-app:master --push .

      # Trigger deployment to EKS for the master environment
      - name: Deploy to EKS
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: deployment
          commit-message: 'Deploy to EKS'
          title: 'Deploy to EKS'
          body: 'Deploy to EKS'
          labels: 'deploy-to-eks'
          reviewers: 'username'
          assignees: 'username'
